name: Java CI

on:
  push:
    branches: [ main, develop ]
    tags: ['v*']
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  # crea la build e testalo
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew.bat build

      - name: Run tests
        run: ./gradlew.bat test

  # Crea il fatty jar per il release
  create-release:
    needs: build-and-test
    #if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Spring Boot fat jar
        run: ./gradlew.bat bootJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-fat-jar
          path: build/libs/*.jar
